import Nav from "@/components/Nav/Nav";
import "./globals.css";
import { AuthContextProvider } from "@/contexts/AuthContext";
import Providers from "@/providers/Providers";
import Toast from "@/components/Toast/Toast";
import { ToastProvider } from "@/providers/ToastProvider";

export const metadata = {
  title: "Score Cards",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ToastProvider>
            <AuthContextProvider>
              <Nav />
              {children}
              <Toast />
            </AuthContextProvider>
          </ToastProvider>
        </Providers>
      </body>
    </html>
  );
}
